# Runtime image for parquet-peek
# Generated by genproj (docker-container capability). Adjust for your application.
FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci || npm install
RUN npm run build

# Copy application source
COPY . .

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s CMD wget -qO- http://127.0.0.1:3000/health || exit 1
# TODO: adjust the start command for your application
# TODO: adjust for your framework output, e.g. SvelteKit adapter-node: CMD ["node", "build/index.js"]
CMD ["node", "build/index.js"]
