# Multi-stage image for parquet-peek
# Generated by genproj (docker-container capability). Adjust for your application.
#
# Stage 1 (build): copies the full source tree, installs dev dependencies and
# builds the application. Stage 2 (runtime): copies only the build output and
# production dependencies, keeping the final image small.

FROM node:22-slim AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

FROM node:22-slim
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/build ./build
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/package-lock.json ./package-lock.json
RUN npm ci --omit=dev
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s CMD node -e "fetch('http://127.0.0.1:3000/health').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))"
CMD ["node", "build/index.js"]
